# -------------------- Configurable options  ---------------------
CC           := gcc
CFLAGS       := -Wall -std=gnu11 -g -Og -pedantic -MMD \
				-Werror=implicit-function-declaration
LDFLAGS      := -lmhash

AST_FILE	  			= test/pass/civic.ast
BIN_DIR 	  			= bin/
DOC_DIR 	  			= doc/
AST_GENERATED_SOURCES 	= src/generated/
AST_GENERATED_HEADERS	= include/generated/
SOURCES   	  			= src/core src/traversal src/passes
TARGET 	 	  			= civcc
DEBUG 					= @
